YGDP-94
yverdon/geocity pull request #115
Opened 2020-09-29 09:46 UTC by monodo

2020-09-29 10:05 UTC, monodo commented
@sephii please review. 3 test broken

2020-11-02 10:53 UTC, sephii requested changes
Il faudrait aussi si possible refaire les commits pour y mettre des messages clairs, là aucun commit n’indique ce qui a été fait (le commit qui contient les features a juste un message "squash". D’ailleurs [ce commit](https://github.com/yverdon/geocity/pull/115/commits/530719dbbc332d148f4c3374f9fb71fada0528c4) a plein d’autres changements qui sont pas liés à YGDP-94, je sais pas ce qui s’est passé).

2020-11-02 10:53 UTC, sephii commented on permits/models.py
> +        on_delete=models.SET_NULL,
Ça ne fait pas de sens de garder des entrées de ce modèle qui ne pointeraient sur aucune entité administrative. J’enlèverais `null=True` et remplacerais `on_delete=models.SET_NULL` par `on_delete=models.CASCADE`.

2020-11-02 10:53 UTC, sephii commented on permits/models.py
> +        verbose_name = _("Status (contrôle l'étape du processus administratif)")
J’appellerais ça genre "Statuts d’entités administratives".

2020-11-02 10:53 UTC, sephii commented on permits/models.py
> +        related_name='enabled_status'
`enabled_statuses` plutôt, vu qu’il y en a plusieurs.

2020-11-02 10:53 UTC, sephii commented on permits/models.py
> +class PermitWorkFlowStatus(models.Model):
`PermitWorkflowStatus` (sans le F majuscule).

2020-11-02 10:53 UTC, sephii commented on permits/models.py
> +    Represents a works object for a specific works type.
Le commentaire ne correspond pas à la réalité.

2020-11-02 10:53 UTC, sephii commented on permits/admin.py
> +    inlines = [
Il me semble que ça aurait plus de sens de mettre une liste à choix multiples plutôt, étant donné la contrainte d’unicité du statut pour l’entité administrative, et le fait qu’il n’y a pas de champ supplémentaire à renseigner.

2020-11-02 10:53 UTC, sephii commented on permits/forms.py
> -            initial = {**kwargs.get('initial', {}), 'administrative_entity': self.instance.administrative_entity}
Pour ces trucs de reformatage, à ta place j’installerais Black (https://github.com/psf/black), je blackifierais tout le code, et j’ajouterais une tâche dans la CI pour vérifier le formatage. Après tu peux configurer le repo pour ignorer le commit de reformatage (https://akrabat.com/ignoring-revisions-with-git-blame/).

2020-11-02 10:53 UTC, sephii commented on permits/forms.py
> +            instance.administrative_entity)
Le code va exploser si `instance` n’est pas passé en kwargs. Il faudrait soit gérer ce cas (en ajoutant une condition pour pas filtrer les choix si pas d’instance), soit obliger `instance` à être passé en paramètre.

2020-11-02 10:53 UTC, sephii commented on permits/management/commands/fixturize.py
> +            choice, created = models.PermitWorkFlowStatus.objects.get_or_create(status=status_value[0], administrative_entity=administrative_entity_yverdon)
```
for entity in [administrative_entity_yverdon, administrative_entity_grandson]:
    models.PermitWorkFlowStatus.objects.get_or_create(status=status_value[0], administrative_entity=entity)
```

2020-11-02 10:53 UTC, sephii commented on permits/migrations/0001_initial.py
> -                ('is_public', models.BooleanField(default=False, verbose_name='Publier')),
Pourquoi avoir modifié cette migration existante? En général c’est pas une bonne idée de modifier des migrations qui ont déjà été appliquées.

2020-11-02 10:53 UTC, sephii commented on permits/services.py
> +def get_status_choices_for_administrative_entity(administrative_entity):
Ajouter une docstring.

2020-11-02 10:53 UTC, sephii commented on permits/services.py
> +    status = models.PermitWorkFlowStatus.objects.filter(
Tu peux pas mal simplifier ce code:

```python
available_statuses = models.PermitWorkFlowStatus.objects.filter(administrative_entity=administrative_entity, status__in=[models.PermitRequest.STATUS_PROCESSING, models.PermitRequest.STATUS_SUBMITTED_FOR_VALIDATION, models.PermitRequest.STATUS_AWAITING_SUPPLEMENT, models.PermitRequest.STATUS_RECEIVED]).values_list("status", flat=True)
statuses_dict = dict(models.PermitRequest.STATUS_CHOICES)

return [(status, statuses_dict[status]) for status in available_statuses]
```

Par contre j’ai l’impression que cette façon de faire (whitelister seulement certains statuts) fonctionne dans le cas d’utilisation actuel (uniquement le formulaire pour demander plus d’infos), mais qu’elle ne fonctionnera pas si elle est utilisée à une autre étape du workflow. À mon avis il faudrait avoir une fonction qui prend en paramètre une entité administrative et qui renvoie les statuts possibles pour cette entité administrative, sans plus de logique que ça, et une autre fonction qui prend en paramètre une liste de statuts et un statut courant, et qui filtre la liste donnée pour renvoyer que les statuts qui sont valables (et après éventuellement une troisième fonction qui combine les deux). Genre:

```python
def get_status_choices_for_administrative_entity(administrative_entity):
    return models.PermitWorkflowStatus.objects.filter(administrative_entity=administrative_entity).values_list("status", flat=True)

def get_status_choices_for_status(status_choices, status):
    if status == models.PermitRequest.STATUS_DRAFT:
        return set(status_choices) & {models.PermitRequest.STATUS_PROCESSING, models.PermitRequest.STATUS_APPROVED, models.PermitRequest.STATUS_REJECTED}
    elif status == ...:
        ...
```

Ça ce serait un vrai workflow de changement de statut.

2020-11-02 10:53 UTC, sephii commented on permits/services.py
> +def get_actions_for_adminentity(actions, administrative_entity):
* Ajouter une docstring (en mentionnant ce que c’est ce `actions`)
* Renommer `adminentity` en `administrative_entity` par souci de cohérence

2020-11-02 10:53 UTC, sephii commented on permits/services.py
> +    for action in actions:
Pour réduire le nombre de requêtes et simplifier le code tu pourrais récupérer la liste des statuts en amont:

```python
available_statuses = get_status_choices_for_administrative_entity(administrative_entity)
required_statuses_for_actions = {
    "request_validation": models.PermitRequest.STATUS_AWAITING_VALIDATION,
    "poke": models.PermitRequest.STATUS_APPROVED,
}

available_actions = [
    action
    for action in actions
    if action not in required_statuses_for_actions or required_statuses_for_actions[action] in available_statuses
]

return available_actions
```

2020-11-02 10:53 UTC, sephii commented on permits/views.py
> +        current_actions = services.get_actions_for_adminentity(self.actions.copy(),
Pas besoin d’utiliser `copy` avec l’approche que j’ai proposée pour cette fonction. Il faudrait dans tous les cas éviter de muter les paramètres dans le corps des fonctions, c’est la porte ouverte aux mauvaises surprises.

2020-11-02 10:53 UTC, sephii commented on permits/views.py
> +            validation, * \
C’est très peu lisible cette ligne (avec le `rest` qui est à la ligne après le `*`). Je te suggère plutôt

```python
validation, *rest = list(
    ...
)
```

2020-11-02 10:53 UTC, sephii commented on status_setup.py
> +from permits import models
À quoi sert ce fichier?

2020-11-06 13:35 UTC, merged