YC-159 Champs de type adresse
yverdon/geocity pull request #176
Opened 2021-01-20 10:42 UTC by monodo

2021-01-26 20:46 UTC, sephii requested changes

2021-01-26 20:46 UTC, sephii commented on permits/templates/permits/permit_request_properties.html
> +  <link rel="stylesheet" type="text/css" href="{% static 'libs/js/jquery-ui-custom/jquery-ui.min.css' %}">
Ce serait mieux de mettre ça [sur le media du widget](https://docs.djangoproject.com/en/3.0/topics/forms/media/) et de mettre `{{ form.media }}` (ce que fait déja YC-89 d’ailleurs je crois).

2021-01-27 13:27 UTC, monodo commented on permits/forms.py
> +                                "single_adress_field": "true",
Oui, c'est moche mais comme ça on est sûr que ça passe de l'autre côté dans le js

2021-01-28 10:44 UTC, sephii commented on permits/forms.py
> +                                "single_adress_field": "true",
Je suis pas monstre convaincu. ^^ Je pense aussi qu’on aurait tout intérêt à créer un `AddressInputWidget` pour éviter la répétition de code (ce dict est répété à au moins 4 endroits dans le code), mais on pourra toujours améliorer ça plus tard.

2021-01-28 10:44 UTC, sephii commented on permits/tests/test_permit_request.py
> +        }
Il manque une partie du test j’ai l’impression!

2021-01-28 12:30 UTC, monodo commented on static/customWidgets/RemoteAutocomplete/remoteautocomplete.js
> +              $("#" + item.id).val(
En fait non car:

jquery a la méthode `val `sur l'objet
`Object { 0: input#id_properties-8_6.form-control.ui-autocomplete-input, length: 1 }`

Mais `item `non
`<input id="id_properties-8_6" class="form-control ui-autocomplete-input" type="text" name="properties-8_6" title="" required="" data_remote_autocomplete="{\"apiurl\": \"https://a…dress_field\": \"true\"}" autocomplete`="off">

donc je propose qu'on laisse comme ça

2021-01-28 12:40 UTC, monodo commented on permits/forms.py
> +                                "single_adress_field": "true",
Ok, c'est changé

2021-01-28 12:43 UTC, sephii commented on static/customWidgets/RemoteAutocomplete/remoteautocomplete.js
> +              $("#" + item.id).val(
Ah oui parce que c’est un élément du dom qui est pas jquerisé, du coup tu peux utiliser `item.value = ...`. ;)

2021-01-28 14:41 UTC, sephii commented
Superseded by https://github.com/yverdon/geocity/pull/186 (with a correctly named branch).

2021-01-28 14:41 UTC, closed without merging