YC-119 contacts optionnels
yverdon/geocity pull request #180
Opened 2021-01-22 18:29 UTC by monodo

Tests to come next week

2021-01-26 10:39 UTC, sephii requested changes

2021-01-26 10:39 UTC, sephii commented on permits/services.py
> +    required_actor_types = models.PermitActorType.objects.filter(
Tu réexécutes la même requête que dans `get_all_configured_actors_types`, ce qui est pas très performant. Il vaudrait mieux réutiliser les actors types récupérés dans `get_all_configured_actors_types`. Je propose ça:

```python
# Dans services.py
def get_actors_types(permit_request):
    return models.PermitActorType.objects.filter(
        works_type__in=get_permit_request_works_types(permit_request)
    ).values_list("type", "is_mandatory")

# Modifier cette fonction pour utiliser `get_actors_types`
def get_missing_actors_types(permit_request):
    existing_actor_types = set(
        permit_request.permit_request_actors.values_list("actor_type", flat=True)
    )
    required_actor_types = set(actor_type for actor_type, is_mandatory in get_actor_types(permit_request) if is_mandatory)

    return required_actor_types - existing_actor_types

# ...

def get_permitactorformset_initiated(permit_request, data=None):
    configured_actor_types = get_actors_types(permit_request)
    actor_initial_forms = [{"actor_type": actor_type[0]} for actor_type in configured_actor_types]

    # Tu peux aussi simplifier ta boucle imbriquée ici
    mandatory_actor_types = {actor_type for actor_type, is_mandatory in configured_actor_types if is_mandatory}
    for form in formset:
        form.empty_permitted = form.initial["actor_type"] not in mandatory_actor_types
```

2021-01-26 10:39 UTC, sephii commented on permits/services.py
> +def get_all_configured_actors_types(permit_request):
Du coup cette fonction peut disparaître.

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        self.works_types = factories.WorksTypeFactory.create_batch(1)
Si tu ne crées qu’un objet pas besoin de `create_batch`: `self.works_type = factories.WorksTypeFactory()`

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        models.WorksObjectType.objects.create(
Tu peux simplifier ce code en enlevant la création explicite des `works_types` et `works_objects` ci-dessus et faire ça comme ça:

```python
self.works_object_type = factories.WorksObjectTypeFactory()
self.works_type = works_object_type.works_type
self.works_object = works_object_type.works_object
```

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        actor_required = models.PermitActorType.objects.create(
Crée une factory pour `PermitActorType` et remplace par `actor_required = factories.PermitActorTypeFactory(is_mandatory=True, works_type=self.works_type)`

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        factories.WorksObjectTypeChoiceFactory.create_batch(
Enlever le `create_batch` et utiliser `factories.WorksObjectTypeChoiceFactory(permit_request=permit_request)`.

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +            "form-0-actor_type": ["0"],
Plutôt qu’un 0 hardcodé ici il faudrait utiliser `actor_required.type`.

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +            follow=True,
Pourquoi suivre la redirection? Il me semble pas que ce soit utile.

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +            data=self.test_formset_data,
Ça m’étonne que ce test passe: tu crées une demande de permis avec un works object type qui ne demande aucun acteur. Peut-être que ça passe dans cette version du code, mais je pense que ça ne va plus passer une fois 109 mergée.

Il faudrait soit enlever toute l’initialisation que tu fais dans `setUp`, soit utiliser le `works_object_type` créé dedans (avec un `factories.WorksObjectTypeFactory(permit_request=permit_request, works_object_type=self.works_object_type)`). Le code au début de ta méthode de test deviendrait donc:

```python
    permit_request = factories.PermitRequestFactory(
            author=self.user.permitauthor, status=models.PermitRequest.STATUS_DRAFT
        )

        factories.WorksObjectTypeFactory(permit_request=permit_request, works_object_type=self.works_object_type)
        permit_request.administrative_entity.works_object_types.set(
            [self.works_object_type]
        )
        prop = factories.WorksObjectPropertyFactory()
        prop.works_object_types.set([self.works_object_type])
```

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        factories.WorksObjectTypeChoiceFactory.create_batch(
Mêmes remarques que dans l’autre test pour l’utilisation du `works_object_type`.

2021-01-26 10:39 UTC, sephii commented on permits/tests.py
> +        self.assertEqual(response.status_code, 200)
Ce serait bien tester un peu plus en profondeur, par exemple en vérifiant que le formulaire a bien une erreur (avec [`assertFormsetError`](https://docs.djangoproject.com/en/dev/topics/testing/tools/#django.test.SimpleTestCase.assertFormsetError), et/ou que l’objet `PermitRequestActor` n’a pas été créé.

2021-01-27 12:41 UTC, monodo commented on permits/tests.py
> +            data=self.test_formset_data,
WorksObjectTypeFactory n'est pas prévu pour prendre des argument @sephii

2021-01-28 13:17 UTC, merged