YC-62 Showing information of responsible service in summary
yverdon/geocity pull request #194
Opened 2021-02-09 09:08 UTC by felicemcc

2021-02-09 10:17 UTC, felicemcc commented
Après clarification avec @monodo:
L'info du service responsable pour chaque objet sera disponible dans le résume dès que ce sera fourni par le secrétariat, donc, s’il n'y a pas encore d'info, la section ne se montre pas.

2021-02-15 16:26 UTC, sephii requested changes

2021-02-15 16:26 UTC, sephii commented on permits/templates/permits/_permit_request_summary.html
> +      {% ifequal works_object_type object %}
Il faudrait plutôt ajouter ces informations dans `get_permit_objects` pour éviter de faire ces comparaisons (c’est pas bon en termes d’efficacité).

Je t’ai mis une suggestion d’implémentation dans mon commentaire sur `services.py`.

2021-02-15 16:26 UTC, sephii commented on permits/services.py
> +            for prop in get_amend_custom_properties_values(permit_request).filter(
De manière générale il faut éviter de faire n * n requêtes en bases de données, sinon les performances deviennent rapidement très mauvaises.

À ta place je récupérerais toutes les valeurs de proprietés custom de la demande avec `get_amend_custom_properties_values` puis j’utiliserais [le template tag `regroup` de Django](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#regroup) pour les regrouper par works object type.

2021-02-15 18:15 UTC, felicemcc commented on permits/templates/permits/_permit_request_summary.html
> +      {% ifequal works_object_type object %}
Le filtering a été fait dans get_permit_objects...

2021-02-15 18:18 UTC, felicemcc commented on permits/services.py
> +            for prop in get_amend_custom_properties_values(permit_request).filter(
J'avais implémenté d'abord avec le regroup tag, mais après, en faisant le filtering depuis get_permit_object j'ai vu qu'il n’avait pas besoin de faire le regrouper. 

Done! Merci...

2021-02-16 06:50 UTC, sephii commented on permits/services.py
> +            amend_custom_properties_values.filter(
Ce code fait toujours n requêtes. Tu pourrais construire le mapping avant la boucle comme ça:

```python
from collections import defaultdict
amend_custom_properties_values = get_amend_custom_properties_values(permit_request)
amend_custom_properties_by_wot = defaultdict(list)
for value in amend_custom_properties_values:
    amend_custom_properties_by_wot[value.works_object_type_choice.works_object_type].append(value)

# Et après tu peux accéder à `amend_custom_properties_by_wot[works_object_type]` pour avoir la liste des custom props.
```

2021-02-16 06:51 UTC, sephii commented on permits/templatetags/permits_extras.py
> +        "amend_custom_properties_values": services.get_amend_custom_properties_values(
Tu devrais enlever ça du coup vu que ce n’est plus utilisé.

2021-02-18 07:12 UTC, merged