Yc 72
yverdon/geocity pull request #204
Opened 2021-03-17 10:11 UTC by anthonyledda

2021-03-29 14:27 UTC, sephii requested changes

2021-03-29 14:27 UTC, sephii commented on permits/admin.py
> +                    (False, "Visible uniquement par les utilisateur autorisés"),
Typo: `utilisateurs`

2021-03-29 14:27 UTC, sephii commented on permits/admin.py
> +                    (False, "Visible uniquement par les utilisateur autorisés"),
Pour éviter de répéter ces choix partout, tu pourrais en faire une constante.

2021-03-29 14:27 UTC, sephii commented on permits/forms.py
> +            if self.user.is_superuser or self.user.has_perm("see_private_demands"):
Le test `is_superuser` est redondant, `has_perm` renvoie déjà `True` si l’utilisateur est superuser.

2021-03-29 14:27 UTC, sephii commented on permits/forms.py
> +            if self.user.is_superuser or self.user.has_perm("see_private_demands"):
Je sortirais aussi le test `has_perm` de la boucle pour des questions de performance.

2021-03-29 14:27 UTC, sephii commented on permits/forms.py
> +                queryset = works_type.works_object_types.filter(
Au lieu d’avoir 2 querysets distincts (et potentiellement d’oublier de modifier l’une ou l’autre des branches), ce serait plus clair d’avoir un seul queryset et de le filtrer si nécessaire:

```python
queryset = works_type.works_object_types.filter(
    administrative_entities=self.instance.administrative_entity,
).distinct().select_related("works_object")

if not self.user.has_perm("see_private_demands"):
    queryset = queryset.filter(is_public=True)
```

2021-03-29 14:27 UTC, sephii commented on permits/models.py
> +            ("see_private_demands", _("Voir les demandes restreintes")),
Je remplacerais `demands` par `requests` parce que c’est le nom qu’on a utilisé partout ailleurs ("permit requests" et pas "permit demands").

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +    if user.is_superuser or user.has_perm("see_private_demands"):
Enlever le `is_superuser` redondant.

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +        return models.WorksType.objects.filter(
Ne pas répéter tout le queryset, ajouter juste le `queryset.filter(is_public=True)` si l’utilisateur n’a pas le permission pour voir les demandes privées.

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +    if user.is_superuser or user.has_perm("see_private_demands"):
Pareil que plus haut: enlever `is_superuser`, ne pas répéter tout le queryset.

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +    if user.is_superuser or user.has_perm("see_private_demands"):
Ter.

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +        if user.is_superuser or user.has_perm("see_private_demands"):
Même remarque qu’avant (`is_superuser` + répétition du queryset).

2021-03-29 14:27 UTC, sephii commented on permits/services.py
> +    if user.is_superuser or user.has_perm("see_private_demands"):
Même remarque que plus haut.

2021-03-29 14:27 UTC, sephii commented on permits/tests/test_permit_request.py
> +        super().setUp()
Pas besoin d’appeler `super().setUp()` dans les tests.

2021-03-29 14:27 UTC, sephii commented on permits/tests/test_permit_request.py
> +        self.works_types = factories.WorksTypeFactory.create_batch(2)
Pourquoi créer tout ça dans le `setUp` et pas simplement dans la méthode de test?

2021-03-29 14:27 UTC, sephii commented on permits/tests/test_permit_request.py
> +        self.administrative_entity = models.PermitAdministrativeEntity.objects.create(
Utiliser les factories?

2021-03-31 07:28 UTC, monodo commented on permits/admin.py
> +                    (False, "Visible uniquement par les utilisateur autorisés"),
En fait, c'était une scorie. Ce choix n'est visible qu'une fois dans l'admin. Mais comme ce type de choix se trouve aussi côté backoffice, j'en fait une constante dans models.py

2021-03-31 07:47 UTC, monodo commented on permits/forms.py
> +                queryset = works_type.works_object_types.filter(
OK, je test

2021-03-31 08:01 UTC, monodo commented on permits/forms.py
> +                queryset = works_type.works_object_types.filter(
Tout bon, j'ai fait ça partout

2021-04-06 08:49 UTC, sephii commented on permits/admin.py
> +                    (False, "Visible uniquement par les utilisateur autorisés"),
Du coup utiliser la constante aussi ici? ^^

2021-04-06 08:49 UTC, sephii commented on permits/models.py
> +PUBLIC_ALL = True
Perso j’irais pas jusqu’à faire des constantes pour des valeurs booléennes, mais c’est toi qui vois. ^^

2021-04-06 08:49 UTC, sephii commented on permits/services.py
> +            pk__in=models.WorksObjectType.objects.filter(is_public=True,).values_list(
Il faudrait filtrer les entités administratives seulement si la personne n’a pas la permission de voir les demandes privées non?

2021-04-06 08:49 UTC, sephii commented on permits/services.py
> +        ).all()
Pas besoin du `.all()`.

2021-04-06 08:49 UTC, sephii commented on permits/tests/test_permit_request.py
> +        administrative_entity = models.PermitAdministrativeEntity.objects.create(
Pourquoi ne pas utiliser les factories? Tu pourrais faire `factories.PermitAdministrativeEntityFactory(name="privateEntity")`

2021-04-06 08:49 UTC, sephii commented on permits/tests/test_permit_request.py
> +    def test_administrative_entity_step_without_public_demands_is_empty_to_standard_user(
C’est bien de tester ce cas, mais il faudrait aussi tester le cas où l’utilisateur a les permissions pour voir les entités privées.

2021-04-06 08:49 UTC, sephii commented on permits/tests/test_permit_request.py
> +        works_types = factories.WorksTypeFactory.create_batch(3)
Tu peux utiliser les factories pour simplifier la création des données initiales:

```python
public_works_object_types = factories.WorksObjectTypeFactory.create_batch(2, is_public=True)
private_works_object_type = factories.WorksObjectTypeFactory(is_public=False)
administrative_entity = factories.PermitAdministrativeEntityFactory()
administrative_entity.works_object_types.set(public_works_object_types + [private_works_object_type])

permit_request = factories.PermitRequestFactory(author=self.user.permitauthor, administrative_entity=administrative_entity)

response = ...
```

2021-04-06 08:49 UTC, sephii commented on permits/tests/test_permit_request.py
> +        public_items_count = str(response.content).count("form-check-label")
Tu ferais mieux d’utiliser `geocity.permits.tests.utils.get_parser` puis `get_parser(response.content).select(".administrative-entity-fieldgroup .form-check-label")`. C’est plus résilient.

2021-04-06 12:21 UTC, monodo commented on permits/models.py
> +PUBLIC_ALL = True
Pas faux ;-)

2021-04-07 05:36 UTC, monodo commented on permits/tests/test_permit_request.py
> +    def test_administrative_entity_step_without_public_demands_is_empty_to_standard_user(
OK: test_administrative_entity_step_without_public_requests_is_visible_to_user_with_specific_permissions

2021-04-07 05:47 UTC, monodo commented on permits/tests/test_permit_request.py
> +        public_items_count = str(response.content).count("form-check-label")
merci!

2021-04-07 06:08 UTC, monodo commented
Thanks for the review @sephii. Merging.

2021-04-07 06:08 UTC, merged