Sprint 6/yc 250 use fk
yverdon/geocity pull request #229
Opened 2021-04-25 20:01 UTC by monodo

2021-05-01 19:36 UTC, monodo commented
Requires Data migration to set all integrator value as integrator-yverdon!

2021-05-18 14:35 UTC, sephii requested changes

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +            if not request.user.is_superuser:
Pareil ici et ci-dessous, inverser les conditions et les branches.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +            if not request.user.is_superuser:
Sur tous ces tests il faudrait plutôt utiliser `get_custom_queryset` (enfin, `filter_for_user` une fois renommé), ça devrait bien raccourcir le code.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Pas besoin de la request mais juste du `user`.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        super(WorksObjectPropertyForm, self).__init__(*args, **kwargs)
Tu peux enlever ce qu’il y a entre parenthèses du `super()`.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Et vu que `user` est requis, ne pas mettre de valeur par défaut à `pop`, pour que ça pète si on ne passe pas de user.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        Form = super(WorksObjectPropertyAdmin, self).get_form(request, obj, **kwargs)
Je comprends pas pourquoi tu dois faire tout ce micmac. Je crois que tu peux juste faire ça:

```python
def get_form(self, request, obj=None, **kwargs):
    return super().get_form(request, obj, dict(kwargs, user=request.user))
```

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Et pas besoin de définir ça sur `self` vu que cette valeur est seulement utilisée ici.

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Même remarque que plus haut:

* Tu as juste besoin de `user` pas de toute la requête
* Pas besoin de définir ça sur `self` parce que cette valeur est utilisée seulement ici

2021-05-18 14:35 UTC, sephii commented on permits/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
cf. plus haut, je pense que tu peux simplifier ça.

2021-05-18 14:35 UTC, sephii commented on permits/tests/test_admin_site.py
> +        self.assertEqual(True, False)
Heu ^^

2021-05-18 18:43 UTC, monodo commented on permits/admin.py
> +                    permitdepartment__integrator=request.user.groups.all()[0].pk,
Directement sur User ou sur une table 1-1 pour étendre User ?

2021-05-18 18:46 UTC, monodo commented on permits/admin.py
> +class UserAdmin(BaseUserAdmin):
Tu peux pas créer un user depuis l'admin car il te manque son extension 1-1 Author qui n'est pas inclue dans l'admin. Je pense qu'on ne devrait pas créer de user via l'admin, ne serait-ce que pour le cas où le 2FA est activé

2021-05-18 18:49 UTC, monodo commented on permits/admin.py
> +    def save_model(self, request, obj, form, change):
Oh merci @sephii, enfin un exemple de Mixin :-)

2021-05-18 18:50 UTC, monodo commented on permits/tests/test_admin_site.py
> +        self.assertEqual(True, False)
Hi

2021-05-25 12:37 UTC, AlexandreJunod commented on permits/admin.py
> +        Form = super(WorksObjectPropertyAdmin, self).get_form(request, obj, **kwargs)
`return super().get_form()` est une fonction récursive

2021-05-27 20:29 UTC, sephii commented on permits/admin.py
> +        Form = super(WorksObjectPropertyAdmin, self).get_form(request, obj, **kwargs)
Pas sûr de comprendre. `super().get_form()` c’est la méthode `get_form` de la classe parente, ce n’est donc pas récursif.

2021-05-28 08:44 UTC, AlexandreJunod commented on permits/admin.py
> +        Form = super(WorksObjectPropertyAdmin, self).get_form(request, obj, **kwargs)
![image](https://user-images.githubusercontent.com/36194606/119956395-59132980-bfa1-11eb-89cf-941ad7ca3d7a.png)
Lorsque la méthode `get_form` de la classe parente est appeler, le code réagis comme ceci

2021-05-31 06:28 UTC, sephii commented on permits/admin.py
> +        Form = super(WorksObjectPropertyAdmin, self).get_form(request, obj, **kwargs)
Ah oui en fait la syntaxe correcte était `super().get_form(request, obj, user=request.user, **kwargs)`, mais ça ne fonctionne pas parce que le [`get_form` de Django](https://github.com/django/django/blob/d270dd584e0af12fe6229fb712d0704c232dc7e5/django/contrib/admin/options.py#L670) renvoie une classe et pas une instance, donc tu peux effectivement pas passer `user` ici. Je vois pas de moyen vraiment plus clean que ce hack du coup.

2021-05-31 13:36 UTC, AlexandreJunod commented on permits/admin.py
> +        if request.user.is_superuser:
Résolu. @monodo veut éviter qu'un superuser puisse abuser des droits pour changer l'émail d'un autre user et envoyer la demande de réinitialisation de mot de passe afin de récupérer son compte

2021-05-31 13:37 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-05-31 13:38 UTC, AlexandreJunod commented on permits/admin.py
> +def get_custom_queryset(self, request, appmodel):
Résolu

2021-05-31 13:38 UTC, AlexandreJunod commented on permits/admin.py
> +def get_custom_readonly_field(request):
Résolu

2021-05-31 13:41 UTC, AlexandreJunod commented on permits/admin.py
> +    obj.integrator = request.user.groups.all()[0]
Résolu. L'integrator admin agît comme un "admin" au sein de son entité administrative, il sera là pour gérer toutes les données et assignée les droits, il est le seul groupe qui à besoin d'accéder à l'admin

2021-05-31 13:42 UTC, AlexandreJunod commented on permits/admin.py
> +def save_object_whith_creator_group(self, request, obj, form, change):
Résolu. Je n'ai pas réussi à me passer du save, je me retrouvais sans integrator admin

2021-05-31 13:42 UTC, AlexandreJunod commented on permits/admin.py
> +        # limit editable fields to protect user data, superuser creation must be down using django shell
Résolu

2021-05-31 13:43 UTC, AlexandreJunod commented on permits/admin.py
> +                "password",
Résolu. Il à été totalement enlevé

2021-05-31 13:43 UTC, AlexandreJunod commented on permits/admin.py
> +                permits_permissions = (
Résolu

2021-05-31 13:43 UTC, AlexandreJunod commented on permits/admin.py
> +                )
Résolu

2021-05-31 13:43 UTC, AlexandreJunod commented on permits/admin.py
> +            if not request.user.is_superuser:
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +                    permitdepartment__integrator=request.user.groups.all()[0].pk,
Résolu. On trie sur `permitdepartment__is_integrator_admin=True`

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +        if not request.user.is_superuser:
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +                Q(
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +        edited_user_groups = Group.objects.filter(
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +        is_integrator_admin = False
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +        if obj.groups.count() > 1 and is_integrator_admin:
Résolu

2021-05-31 13:45 UTC, AlexandreJunod commented on permits/admin.py
> +            messages.error(
Résolu

2021-05-31 13:47 UTC, AlexandreJunod commented on permits/admin.py
> +    def save_model(self, request, obj, form, change):
Résolu. Une review pourrait être nécessaire pour les méthodes `clean_groups `et `clean_is_integrator_admin`

2021-05-31 13:47 UTC, AlexandreJunod commented on permits/admin.py
> +# Define a Form for Department
Résolu

2021-05-31 13:47 UTC, AlexandreJunod commented on permits/admin.py
> +# Re-register UserAdmin
Résolu

2021-05-31 13:47 UTC, AlexandreJunod commented on permits/admin.py
> +            if not request.user.is_superuser:
Résolu

2021-05-31 13:47 UTC, AlexandreJunod commented on permits/admin.py
> +        if not request.user.is_superuser:
Résolu

2021-05-31 13:48 UTC, AlexandreJunod commented on permits/admin.py
> +# Define a new Group admin form
Résolu

2021-05-31 13:49 UTC, AlexandreJunod commented on permits/admin.py
> +# Define a new Group admin
Résolu

2021-05-31 13:49 UTC, AlexandreJunod commented on permits/admin.py
> +            user_departments = models.PermitDepartment.objects.filter(
Résolu

2021-05-31 13:49 UTC, AlexandreJunod commented on permits/admin.py
> +                user_groups[0].permitdepartment.is_integrator_admin
Résolu. Aucun cas, condition améliorée

2021-05-31 13:50 UTC, AlexandreJunod commented on permits/admin.py
> +        qs = appmodel.objects.filter(integrator__in=request.user.groups.all())
Résolu

2021-05-31 13:50 UTC, AlexandreJunod commented on permits/admin.py
> +                obj.permitdepartment.integrator = user_groups[0].pk
Résolu

2021-05-31 13:50 UTC, AlexandreJunod commented on permits/admin.py
> +            if not request.user.is_superuser:
Résolu

2021-05-31 13:50 UTC, AlexandreJunod commented on permits/admin.py
> +# Re-register GroupAdmin
Résolu

2021-05-31 13:50 UTC, AlexandreJunod commented on permits/admin.py
> +        qs = qs.filter(integrator__in=request.user.groups.all())
Résolu

2021-05-31 13:51 UTC, AlexandreJunod commented on permits/admin.py
> +        if not request.user.is_superuser:
Résolu

2021-05-31 13:51 UTC, AlexandreJunod commented on permits/admin.py
> +    def save_model(self, request, obj, form, change):
Résolu

2021-05-31 13:51 UTC, AlexandreJunod commented on permits/admin.py
> +            if not request.user.is_superuser:
Résolu

2021-05-31 13:51 UTC, AlexandreJunod commented on permits/admin.py
> +            if not request.user.is_superuser:
Résolu

2021-05-31 13:51 UTC, AlexandreJunod commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Résolu

2021-05-31 13:52 UTC, AlexandreJunod commented on permits/admin.py
> +        super(WorksObjectPropertyForm, self).__init__(*args, **kwargs)
Résolu

2021-05-31 13:52 UTC, AlexandreJunod commented on permits/admin.py
> +        self.request = kwargs.pop("request", None)
Résolu

2021-05-31 13:52 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
Résolu

2021-05-31 13:54 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
Ne peut pas être appliqué sans créer une fonction récursive

2021-05-31 13:55 UTC, AlexandreJunod commented on permits/tests/test_admin_site.py
> +        self.assertEqual(True, False)
Pas résolu

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +class UserAdminForm(forms.ModelForm):
Tu devrais étendre `django.contrib.auth.forms.UserChangeForm` qui fait un `select_related` sur les content types (et qui t’économise 150 requêtes SQL).

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    class Meta:
Tu peux aussi enlever ça vu que `UserChangeForm` le définit déjà.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    class Meta:
Enlever ça, ça n’a aucun effet (le `register` est fait plus bas).

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +        obj.save()
Plutôt `super().save_model(request, obj, form, change)`.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    obj.save()
Plutôt `super().save_model(request, obj, form, change)`.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +                ).select_related("content_type")
Pas besoin du `select_related` ici vu que c’est juste utilisé comme subquery.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +                permits_permissions = Permission.objects.filter(
Je suis pas sûr de comprendre pourquoi on filtre les permissions disponibles pour les superutilisateurices, ça me semble un peu casse-gueule dans le cas où on voudrait avoir un groupe qui a des permissions qui ne concernent pas seulement les permis. L’autre risque de filtrer ces permissions, c’est si un superadmin crée un groupe et qu’un intégrateur (qui fait partie du même groupe d’intégration) modifie ce groupe, alors ça va enlever les permissions auxquelles l’intégrateur n’a pas accès.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +        qs = super().get_queryset(request)
Il faut enlever cette ligne, elle écrase le queryset juste en-dessus.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Est-ce que tu redéfinis cette méthode pour éviter d’appeler celle du mixin? Si oui, il faudrait alors enlever le `super().get_queryset(request)` plus bas. Si non, il faudrait enlever toute la méthode puisqu’elle ne sert à rien.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    ):  # TODO: Check if get_form can be simplified without making a recursive function (https://github.com/yverdon/geocity/pull/229#discussion_r634437716)
Enlever le commentaire.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Même commentaire que ci-dessus, cette méthode n’a pas de sens.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Comme ci-dessus, cette méthode n’a pas de sens.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Comme ci-dessus, cette méthode n’a pas de sens.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    ):  # TODO: Check if get_form can be simplified without making a recursive function (https://github.com/yverdon/geocity/pull/229#discussion_r634437716)
Enlever le commentaire.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Comme ci-dessus, cette méthode n’a pas de sens.

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +            if request.user.is_superuser:
Remplacer tout ça par `kwargs["queryset"] = filter_for_user(request.user, models.WorksType.objects.all())`

2021-05-31 15:23 UTC, sephii commented on permits/admin.py
> +    def get_queryset(self, request):
Comme plus haut, cette méthode n’a pas de sens.

2021-06-01 06:32 UTC, AlexandreJunod commented on permits/admin.py
> +        save_object_with_creator_group(user, obj)
Résolu

2021-06-01 06:32 UTC, AlexandreJunod commented on permits/admin.py
> +        index_together = ["name", "group"]
Résolu

2021-06-01 06:34 UTC, AlexandreJunod commented on permits/admin.py
> +        print(user_has_integrator_group)
Résolu

2021-06-01 06:34 UTC, AlexandreJunod commented on permits/admin.py
> +        group_name = self.data["name"]
Résolu

2021-06-01 07:00 UTC, AlexandreJunod commented on permits/admin.py
> +    def clean_is_integrator_admin(self):
Pas réalisé. Le message d'erreur est moins bien placé. Pour celui-ci on à privilégié la simplicité du message d'erreur plutôt qu'un  code mieux optimisé

2021-06-01 07:59 UTC, AlexandreJunod commented on permits/admin.py
> +        user_has_integrator_group = any(
Résolu

2021-06-01 08:00 UTC, AlexandreJunod commented on permits/admin.py
> +        index_together = ["description", "permitdepartment"]
Résolu

2021-06-01 08:05 UTC, AlexandreJunod commented on permits/admin.py
> +class UserAdminForm(forms.ModelForm):
Résolu

2021-06-01 08:35 UTC, AlexandreJunod commented on permits/admin.py
> +    class Meta:
Résolu

2021-06-01 08:39 UTC, AlexandreJunod commented on permits/admin.py
> +    class Meta:
Résolu

2021-06-01 08:39 UTC, AlexandreJunod commented on permits/admin.py
> +        obj.save()
Résolu

2021-06-01 08:39 UTC, AlexandreJunod commented on permits/admin.py
> +    obj.save()
Résolu

2021-06-01 08:40 UTC, AlexandreJunod commented on permits/admin.py
> +                ).select_related("content_type")
Résolu

2021-06-01 10:45 UTC, AlexandreJunod commented on permits/admin.py
> +                permits_permissions = Permission.objects.filter(
Résolu

2021-06-01 10:46 UTC, AlexandreJunod commented on permits/admin.py
> +        qs = super().get_queryset(request)
Résolu

2021-06-01 10:49 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-06-01 10:49 UTC, AlexandreJunod commented on permits/admin.py
> +    ):  # TODO: Check if get_form can be simplified without making a recursive function (https://github.com/yverdon/geocity/pull/229#discussion_r634437716)
Résolu

2021-06-01 10:50 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-06-01 10:51 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-06-01 10:51 UTC, AlexandreJunod commented on permits/admin.py
> +    ):  # TODO: Check if get_form can be simplified without making a recursive function (https://github.com/yverdon/geocity/pull/229#discussion_r634437716)
Résolu

2021-06-01 10:51 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-06-01 10:52 UTC, AlexandreJunod commented on permits/admin.py
> +    def get_queryset(self, request):
Résolu

2021-06-01 10:54 UTC, AlexandreJunod commented on permits/admin.py
> +            if request.user.is_superuser:
Résolu

2021-06-01 20:14 UTC, sephii commented on permits/admin.py
> +    def clean_is_integrator_admin(self):
Ce n’est pas une question d’optimisation mais de fonctionnement. Rien ne te garantit que tu as accès à des valeurs de `cleaned_data` autres que `is_integrator_admin` ici. C’est important de mettre cette validation dans `clean` sinon tu risques d’avoir des comportements de validation aléatoires. Tu peux sans problème indiquer à Django que le message d’erreur concerne le champ `is_integrator_admin` en envoyant une erreur de validation comme ça: `raise ValidationError({"is_integrator_admin": "Bla bla bla"})`.

2021-06-02 07:21 UTC, AlexandreJunod commented on permits/admin.py
> +    def clean_is_integrator_admin(self):
Merci ! :)

2021-06-08 12:53 UTC, merged