add token authentication for rest/permits api and filter request by ip
yverdon/geocity pull request #396
Opened 2022-02-03 11:02 UTC by monodo

2022-02-15 14:02 UTC, danickfort-liip requested changes
@monodo J'ai trouvé un bug et quelques remarques/questionnements concernant cette PR.

2022-02-22 16:34 UTC, monodo commented on permits/services.py
> +        and socket.gethostbyname("qgisserver") == request.META["REMOTE_ADDR"]
Non, c'est déterminé dans la composition docker

2022-02-23 10:31 UTC, monodo commented on permits/services.py
> +    for whitelisted_ip in config.IP_WHITELIST:
Done

2022-02-23 10:33 UTC, monodo commented on permits/services.py
> +    for whitelisted_ip in config.IP_WHITELIST:
Ok pour toi @danickfort-liip https://github.com/yverdon/geocity/blob/yc-578/permits/tests/test_permit_request_api.py#L306-L318 ?

2022-02-23 10:54 UTC, danickfort-liip commented on permits/services.py
> +    for whitelisted_ip in config.IP_WHITELIST:
OK 👍

2022-03-01 08:07 UTC, danickfort-liip approved these changes

2022-03-03 13:50 UTC, rbovard commented
Thanks a lot! It's working fine on my side, with defining ip in `IP_WHITELIST` or range in `NETWORK_WHITELIST`.

Question: should we keep the default values? It will be more secure if by default nothing is set when enabling `DRF_ALLOW_TOKENAUTHENTICATION`.

2022-03-03 13:54 UTC, rbovard requested changes

2022-03-03 13:54 UTC, rbovard commented on env.demo
> +DRF_ALLOW_TOKENAUTHENTICATION=False
Missing new line

2022-03-03 13:54 UTC, rbovard commented on permits/services.py
> +        and socket.gethostbyname("qgisserver") == request.META["REMOTE_ADDR"]
Need to use `get_client_ip()`?

2022-03-03 13:54 UTC, rbovard commented on geomapshark/settings.py
> +        "Réseaux  autorisés pour l'utilisation de l'API complète (/rest/permits), séparées par des ','",
```suggestion
        "Réseaux autorisés pour l'utilisation de l'API complète (/rest/permits), séparés par des ','",
```

2022-03-03 13:54 UTC, rbovard commented on geomapshark/settings.py
> +        "IP  autorisées pour l'utilisation de l'API complète (/rest/permits), séparées par des ','",
```suggestion
        "IP autorisées pour l'utilisation de l'API complète (/rest/permits), séparées par des ','",
```

2022-03-03 14:14 UTC, rbovard approved these changes

2022-03-03 14:16 UTC, merged