YC-609: Improve backoffice tabs
yverdon/geocity pull request #405
Opened 2022-02-09 11:05 UTC by rbovard

Fix https://jira.liip.ch/browse/YC-609

Please review.

2022-02-09 12:04 UTC, monodo requested changes

2022-02-09 12:04 UTC, monodo commented on permits/templates/permits/_permit_request_actions.html
> +              <a class="btn btn-primary btn-action nav-link{% if active_form == "amend" %} active{% endif %}" id="amend-tab" data-toggle="tab" href="#amend" role="tab" aria-controls="amend" aria-sele
Well "Traitement" is also not perfect...

2022-02-09 12:20 UTC, rbovard commented on permits/templates/permits/_permit_request_actions.html
> +              <a class="btn btn-primary btn-action nav-link{% if active_form == "amend" %} active{% endif %}" id="amend-tab" data-toggle="tab" href="#amend" role="tab" aria-controls="amend" aria-sele
Yes, it was the reason I tried to replace "Traitement" with something...

Any suggestion?

2022-02-09 12:21 UTC, rbovard commented on permits/templates/permits/_permit_request_actions.html
> +              <a class="btn btn-primary btn-action nav-link{% if active_form == "amend" %} active{% endif %}" id="amend-tab" data-toggle="tab" href="#amend" role="tab" aria-controls="amend" aria-sele
About the action, a pilot has no obligation to go in this tab, the important one is the send the permit to validation.

2022-02-09 14:58 UTC, rbovard commented on permits/templates/permits/_permit_request_actions.html
> +              <a class="btn btn-primary btn-action nav-link{% if active_form == "amend" %} active{% endif %}" id="amend-tab" data-toggle="tab" href="#amend" role="tab" aria-controls="amend" aria-sele
If you prefer, I can keep Traitement (even if I think Général is better).

2022-02-10 10:27 UTC, monodo approved these changes

2022-02-10 10:27 UTC, merged