YC-604: Add type name in email subject
yverdon/geocity pull request #408
Opened 2022-02-15 16:04 UTC by rbovard

Fix https://jira.liip.ch/browse/YC-604

Please review.

2022-02-16 10:54 UTC, rbovard commented
@monodo I fixed most of the test with adapting the mail subjects. But I don't understand why the remaining tests are failling, can you help me?

2022-03-04 09:16 UTC, rbovard commented
@monodo As discussed, only displaying the unique type names in subject.

Could you please help me with the test?

2022-04-05 12:40 UTC, rbovard commented
Thanks a lot @AlexandreJunod!

@monodo I've rebased the PR, could you please review and merge?

2022-04-05 12:47 UTC, monodo requested changes

2022-04-05 12:47 UTC, monodo commented on permits/services.py
> +
In one line maybe ?
`works_object_types.all().values_list("work_type_name")`

2022-04-05 12:47 UTC, monodo commented on permits/services.py
> +
Create a function in services.py for a DRYer approach ?

2022-04-05 12:47 UTC, monodo commented on permits/services.py
> +
idem

2022-04-05 12:47 UTC, monodo commented on permits/views.py
> +
idem, please use a DRYer approach

2022-04-05 12:47 UTC, monodo commented on permits/views.py
> +
idem

2022-04-05 12:47 UTC, monodo commented on permits/views.py
> +
idem

2022-04-06 07:53 UTC, monodo approved these changes

2022-04-06 07:54 UTC, merged