Yc 645
yverdon/geocity pull request #425
Opened 2022-03-11 15:11 UTC by AlexandreJunod

2022-03-14 10:48 UTC, monodo requested changes

2022-03-14 10:48 UTC, monodo commented on permits/api.py
> +        Replace "my_search" by the text/words you want to find
Add example for search by date, user name, etc.. ?

2022-03-14 10:48 UTC, monodo commented on permits/api.py
> +        limit = int(limit_params) if limit_params and limit_params.isdigit() else 5
use `limit_params = self.request.query_params.get("limit", 5)` instead as shorhand syntax ?

2022-03-14 10:48 UTC, monodo commented on permits/tests/test_permit_request_api.py
> +
Add test to check that unauthentified/unauthorized user can't get results for permits he has no right to see

2022-03-15 10:22 UTC, AlexandreJunod commented on permits/api.py
> +        limit = self.request.query_params.get("limit", 5)
Cette solution ne nous permet pas de gérer l'input de données autre que numériques, ce qui cause l'erreur suivante `invalid literal for int() with base 10: '1a'` et donc le 5 devra forcément être rentré en dehors du `get("limit")`. J'ai opter pour la solution de départ de départ

2022-03-15 12:21 UTC, monodo approved these changes

2022-03-16 10:03 UTC, merged