Fixturize and group fix
yverdon/geocity pull request #659
Opened 2022-12-20 13:11 UTC by AlexandreJunod

2022-12-23 07:55 UTC, monodo requested changes

2022-12-23 07:55 UTC, monodo commented on geocity/apps/accounts/admin.py
> +
I would suggest to move that part to the `Report `model

2023-01-11 14:55 UTC, AlexandreJunod commented on README.md
> +```
remove

2023-01-11 14:55 UTC, AlexandreJunod commented on geocity/apps/forms/migrations/0015_merge_20230110_0919.py
> +        ("forms", "0008_alter_field_integrator_alter_form_integrator_and_more"),
prevent this migrations

2023-01-18 11:44 UTC, rbovard commented on geocity/apps/accounts/templates/accounts/admin/administrative_entity_change.html
> +<<<<<<< HEAD
Warning, merge issue...

2023-01-18 15:06 UTC, merged