YC-1021: Minor improvements for payment
yverdon/geocity pull request #673
Opened 2023-01-18 16:00 UTC by rbovard

Fix https://jira.liip.ch/browse/YC-1021

2023-01-24 10:53 UTC, rbovard commented
@AlexandreJunod As discussed I let you handle the date and page number I removed from default print template.

2023-01-24 13:14 UTC, AlexandreJunod requested changes

2023-01-24 13:14 UTC, AlexandreJunod commented on geocity/apps/reports/templates/reports/report.css
> -  }
Create block and find a way to add in python a counter, date time, and more.. https://www.quackit.com/css/at-rules/css_top-left-corner_at-rule.cfm (keep this in comment)

2023-02-01 14:48 UTC, rbovard commented on geocity/apps/reports/models.py
> +        help_text=_("Taille de la police (en pixels). S'applique a tout le document"),
```suggestion
        help_text=_("Taille de la police (en pixels). S'applique à tout le document"),
```

2023-02-01 14:48 UTC, rbovard commented on geocity/apps/reports/migrations/0020_style_rename_font_reportlayout_font_family_and_more.py
> +                help_text="Taille de la police (en pixels). S'applique a tout le document",
```suggestion
                help_text="Taille de la police (en pixels). S'applique à tout le document",
```

2023-03-01 08:46 UTC, AlexandreJunod commented
Write test with a nice layout and more blocks

2023-03-02 15:14 UTC, AlexandreJunod commented
Add Contact and details to show the sections correctly
Update author to show more informations
Add a planning to show dates
Add validations
Add somme amend properties

2023-03-06 14:59 UTC, AlexandreJunod approved these changes

2023-03-06 15:22 UTC, merged