wip
yverdon/geocity pull request #676
Opened 2023-01-20 09:28 UTC by monodo

2023-01-24 14:45 UTC, rbovard commented on geocity/apps/submissions/views.py
> +    print(entities)
Remove that

2023-01-25 15:04 UTC, rbovard commented
Something is not working.

An user in a group with `see_private_submissions` permission should see **ONLY** the private forms of the admin entity of the group he's belong to. Currently, he can see **ALL** private forms if he's in a group with `see_private_submissions` permission.

2023-01-25 15:05 UTC, rbovard requested changes
Something is not working.

An user in a group with `see_private_submissions` permission should see **ONLY** the private forms of the admin entity of the group he's belong to. Currently, he can see **ALL** private forms if he's in a group with `see_private_submissions` permission.

*Edit: when I said "see private form", it's public + private forms of course*

2023-01-27 15:12 UTC, rbovard reviewed
It's working fine, thanks!

2023-02-20 09:30 UTC, AlexandreJunod requested changes

2023-02-20 09:30 UTC, AlexandreJunod commented on geocity/apps/submissions/forms.py
> +                forms_filter &= Q(is_public=True)
use `get_administrative_entities_with_forms`

2023-02-20 09:30 UTC, AlexandreJunod commented on geocity/apps/submissions/forms.py
> +            ) | Q(is_public=True)
Same condition as line 196 to 202

2023-02-23 13:56 UTC, AlexandreJunod approved these changes

2023-02-24 08:01 UTC, monodo commented on geocity/apps/submissions/forms.py
> +                forms_filter &= Q(is_public=True)
Couldn't we avoid to duplicate logic that is already here: https://github.com/yverdon/geocity/pull/676/files#diff-401ab1dedecd4ec91024d12d0d554a535a6edde585f43caffb7147368fec1ebbR105 ?

2023-02-24 10:18 UTC, rbovard commented
@AlexandreJunod Thanks a lot, if it's ok for you I'll test after you adress @monodo review.

2023-02-24 15:00 UTC, AlexandreJunod commented
Add lock https://fontawesome.com/icons/lock?s=regular&f=classic on the list of private forms so we can distinguish them

2023-02-27 07:44 UTC, AlexandreJunod commented on geocity/apps/accounts/models.py
> +# Controls who can fill each Form
anonymous forms can be filled by anyone

2023-03-01 09:33 UTC, AlexandreJunod commented
@rbovard monodo review is done, tests should normally pass, you can test

2023-03-01 10:46 UTC, rbovard requested changes
The visiblity of private/public form is working well but I noticed a regression.

When there is only one form in an entity, the user should be redirected to the step "Details" and not "Objets" (it's the case in current `develop`)

2023-03-01 11:18 UTC, monodo commented
> re is only one form in an entity, the user should be r



> The visiblity of private/public form is working well but I noticed a regression.
> 
> When there is only one form in an entity, the user should be redirected to the step "Details" and not "Objets" (it's the case in current `develop`)

Cannot reproduce on local instance 🤔

2023-03-01 12:32 UTC, rbovard commented
![image](https://user-images.githubusercontent.com/4549666/222140312-2df7fdd5-721a-498a-bc01-989de89f783d.png)

2023-03-01 15:53 UTC, monodo commented
> ![image](https://user-images.githubusercontent.com/4549666/222140312-2df7fdd5-721a-498a-bc01-989de89f783d.png)

Looks like its related to specific config. I suggest to open a specific issue.

2023-03-01 15:58 UTC, rbovard approved these changes
> Looks like its related to specific config. I suggest to open a specific issue.

https://jira.liip.ch/browse/YC-1049

2023-03-02 08:12 UTC, merged