YC-631: Add sent_date in API
yverdon/geocity pull request #748
Opened 2023-03-21 15:48 UTC by rbovard

Fix https://jira.liip.ch/browse/YC-631

Only 2nd commit is relevant for review.

2023-03-22 12:15 UTC, monodo requested changes

2023-03-22 12:15 UTC, monodo commented on geocity/apps/submissions/models.py
> +        return self.get_sent_date()
useful ? why not use directly `get_sent_date `?

2023-03-22 12:15 UTC, monodo commented on geocity/apps/submissions/models.py
> +        return sent_date
Please avoid loops in api. But I don't know if django-simple-history supports additional filters ?

2023-03-22 16:41 UTC, rbovard commented
@monodo Comments addressed, please review.

2023-03-24 12:43 UTC, monodo approved these changes

2023-03-24 12:44 UTC, merged