solve perf issue and add sent_date where pertinent
yverdon/geocity pull request #829
Opened 2023-06-05 12:39 UTC by monodo

2023-06-06 13:28 UTC, rbovard requested changes

2023-06-06 13:28 UTC, rbovard commented on geocity/apps/submissions/models.py
> +    # TODO: rename on next API break => (last_sent_at)
Are you sure it's neccessary?

2023-06-06 13:28 UTC, rbovard commented on geocity/apps/submissions/migrations/0018_change_sent_date_into_field.py
> +def set_sent_date_from_simple_history(apps, schema_editor):
There is an issue with the migration:

```
Running migrations:
  Applying submissions.0018_change_sent_date_into_field...Traceback (most recent call last):
  File "/code/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line  
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards        
    state = self.apply_migration(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards  
    self.code(from_state.apps, schema_editor)
  File "/code/geocity/apps/submissions/migrations/0018_change_sent_date_into_field.py", line 11, in set_sent_date_from_simple_history
    row.history.filter(status=Submission.STATUS_SUBMITTED_FOR_VALIDATION)
AttributeError: 'Submission' object has no attribute 'history'
```

2023-06-07 06:08 UTC, monodo commented on geocity/apps/submissions/migrations/0018_change_sent_date_into_field.py
> +def set_sent_date_from_simple_history(apps, schema_editor):
Could you please pull & try again ?

2023-06-09 13:22 UTC, rbovard submitted a review, later dismissed
Hum, the migration no longer crashes, but the result is not as expected. On my preprod, only the submissions with `STATUS_SUBMITTED_FOR_VALIDATION` have a sent date, not the other ones. All the submission exept `STATUS_DRAFT` should have a sent_date.

And if an user only has drafts, they are dispayed in the wrong order. Please add extra order field on the creation date to also sort drafts.

2023-06-12 07:44 UTC, monodo commented
> `STATUS_SUBMITTED_FOR_VALIDATION`



> Hum, the migration no longer crashes, but the result is not as expected. On my preprod, only the submissions with `STATUS_SUBMITTED_FOR_VALIDATION` have a sent date, not the other ones. All the submission exept `STATUS_DRAFT` should have a sent_date.
> 
> And if an user only has drafts, they are dispayed in the wrong order. Please add extra order field on the creation date to also sort drafts.

Fixed

2023-06-12 09:03 UTC, AlexandreJunod requested changes

2023-06-12 09:03 UTC, AlexandreJunod commented on geocity/apps/submissions/search.py
> +        MatchType.SENT_DATE: _("Date de création"),
Text is no longer `_("Date de création"),`

2023-06-12 09:03 UTC, AlexandreJunod commented on geocity/apps/submissions/templates/submissions/submission_delete.html
> +      <li>{% translate "Demande du:"%} {{ submission.sent_date }}</li>
Change `Demande du` ?

2023-06-12 13:21 UTC, merged