YC-1143 - Bypass max submissions
yverdon/geocity pull request #878
Opened 2023-10-05 09:50 UTC by danickfort

2023-10-06 09:35 UTC, rbovard requested changes
Works fine, thanks a lot.

I've some remarks and made some code suggestions

2023-10-06 09:35 UTC, rbovard commented on geocity/apps/forms/migrations/0027_rename_max_submissions_bypass_authorized_form_max_submissions_bypass_enabled.py
Is possible to squash the migrations?

2023-10-06 09:35 UTC, rbovard commented on geocity/apps/forms/migrations/0026_form_max_submissions_bypass_authorized.py
> +                verbose_name="Autoriser les utilisateurs avec permission à soumettre des demandes même si le nombre maximal est atteint",
```suggestion
                verbose_name="Autoriser le secrétariat à soumettre des demandes même si le nombre maximal est atteint",
```

2023-10-06 09:35 UTC, rbovard commented on geocity/apps/forms/models.py
> +            "Autoriser les utilisateurs avec permission à soumettre des demandes même si le nombre maximal est atteint"
```suggestion
            "Autoriser le secrétariat à soumettre des demandes même si le nombre maximal est atteint"
```

2023-10-06 09:35 UTC, rbovard commented on geocity/apps/submissions/forms.py
> +                        form_name = f"{form_name} <s>{max_submission_msg}</s> <span class='px-5 text-danger'>(formulaire actif pour l'utilisateur courant)</span>"
```suggestion
                        form_name = f"{form_name} <s class="text-danger">{max_submission_msg}</s> <span class='text-danger'>(formulaire actif pour l'utilisateur courant)</span>"
```

2023-10-10 08:48 UTC, rbovard commented on geocity/apps/submissions/forms.py
> +                        form_name = f"{form_name} <s class='text-danger'>{max_submission_msg}</s> <span class='px-5 text-danger'>(formulaire actif pour l'utilisateur courant)</span>"
```suggestion
                        form_name = f"{form_name} <s class='text-danger'>{max_submission_msg}</s> <span class='pl-1 text-danger'>(formulaire actif pour l'utilisateur courant)</span>"
```

2023-10-10 08:52 UTC, rbovard approved these changes
Thanks a lot!

(I've just done a little style adaptation)

2023-10-10 08:59 UTC, rbovard commented
@danickfort Could you please just check the conflict due to the merge of #877? I think it's pretty straightforward but I prefer to let you do that. After that you can merge.

2023-10-10 09:10 UTC, danickfort commented
> @danickfort Could you please just check the conflict due to the merge of #877? I think it's pretty straightforward but I prefer to let you do that. After that you can merge (edit: after the tests are green ;)).

Done 👍

2023-10-10 09:31 UTC, merged