Service fee for submission yc 785
yverdon/geocity pull request #925
Opened 2024-01-19 11:58 UTC by monodo

Superseeds https://github.com/yverdon/geocity/pull/903

2024-01-23 15:53 UTC, monodo reviewed
@nicolas-heigvd please check the 2 questions

2024-01-23 15:53 UTC, monodo commented on geocity/settings.py
> +DATE_INPUT_FORMATS = [
@nicolas-heigvd is there any specific reason for adding all these formats ?

2024-01-23 15:53 UTC, monodo commented on geocity/apps/core/static/js/messages_timer.js
> +// Get all messages of the alert-success class
@nicolas-heigvd can't you control this in the https://docs.djangoproject.com/en/5.0/ref/contrib/messages/ ?

2024-01-25 07:58 UTC, monodo commented on geocity/apps/submissions/models.py
> +        department = get_departments(user).first()
What happens if the first departement is a validator one ?

2024-01-25 07:58 UTC, monodo commented on geocity/apps/submissions/payments/models.py
> -    @property
⚠️ this is used in template why do you want to remove @nicolas-heigvd ?

2024-01-25 07:58 UTC, monodo commented on geocity/apps/submissions/payments/models.py
> +    # Use the other ones, e.g. provided_*
Where do you update these fields @nicolas-heigvd ?

2024-01-25 07:58 UTC, monodo commented on geocity/apps/submissions/shortcuts.py
> +def get_submission_for_user_or_404(user, submission_id, statuses=None):
Any reason for this change @nicolas-heigvd ?

2024-01-25 07:58 UTC, monodo commented on geocity/apps/submissions/shortcuts.py
> +        # TODO: this is not raised properly: FIXME.
What is the proper way to raise this error then @nicolas-heigvd ?

2024-01-25 07:58 UTC, monodo commented on reset.sh
> +#!/bin/bash
Please add a security to make sure this can NOT be run on production instance ⚠️ @nicolas-heigvd

2024-01-25 07:58 UTC, monodo commented on geocity/urls.py
> +    urlpatterns
Not sure what is the rational for this change @nicolas-heigvd

2024-01-25 07:58 UTC, monodo commented on geocity/settings.py
> -            "level": "ERROR",
Any rational for this change @nicolas-heigvd ?

2024-01-25 08:45 UTC, monodo commented on geocity/apps/submissions/models.py
> +        department = get_departments(user).first()
fixed

2024-02-09 09:50 UTC, danickfort requested changes
@monodo Hello, voici quelques commentaires sur le code pour la feature de service fee

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/payments/models.py
> +                float(self.hourly_rate) * self.time_spent_on_task.total_seconds() / 3600
Pour faire de l'arithmétique avec des montants monétaires, il faudrait utiliser la classe `Decimal` du package `decimal`, pour éviter des erreurs potentielles de précision avec `float`.

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/forms.py
> +            permit_department__is_integrator_admin=False,
Sauf erreur, je pense que c'est superflu de vérifier `is_integrator_admin=False`, vu que ce qui nous intérésse c'est de trouver les groupes de l'entité admin actuelle et qui sont `is_backoffice` et/ou `is_validator`.

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/forms.py
> +        self.mode = kwargs.pop("mode", None)
Pourquoi `self.submission` et `self.mode` ? Il me semble que des variables locales auraient plus de sens

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/views.py
> +                raise Http404
Pour les trois instances de `raise Http404` de cette méthode, je pense que ca serait plus correct de faire quelque chose du genre (adapter le message d'erreur et la redirectation):
```
        messages.add_message(
            request,
            messages.ERROR,
            _(
                "Vous n'avez pas la permission d'effectuer ce changement"
            ),
        )
        return redirect(service_fee_form_page)
```

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/forms.py
> +
Ici, je pense qu'il faudrait vérifier si: le montant total n'est pas <= 0.00. A vérifier au niveau des besoins business (dans le cas de remboursements, valeur négatives auraient du sens ?!).

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/templates/submissions/submission_service_fees.html
> +    </form>
Idée: ajouter ici, après les champs du formulaire, un champ "read-only" avec le montant du tarif de base, pour rappel

2024-02-09 09:50 UTC, danickfort commented on geocity/apps/submissions/forms.py
> +
Pour afficher le nom/prénom de l'utilisateur  plutôt que le username dans le select `provided_by`:
`self.fields["provided_by"].label_from_instance = lambda obj: f"{obj.get_full_name()}"`

2024-02-28 13:07 UTC, monodo commented on geocity/apps/submissions/shortcuts.py
> +    Return list of validator users for provided_by field.
validator => validators

2024-02-28 15:54 UTC, merged